const people = [
        {
            "adult": false,
            "gender": 2,
            "id": 73421,
            "known_for_department": "Acting",
            "name": "Joaquin Phoenix",
            "original_name": "Joaquin Phoenix",
            "popularity": 15.681,
            "profile_path": "/1UzIGSKFH0A9ouwnMwQQWUiqV2s.jpg",
            "cast_id": 357,
            "character": "Arthur Fleck / Joker",
            "credit_id": "5e8593bd98f1f10014aacb71",
            "order": 0
        },
        {
            "adult": false,
            "gender": 2,
            "id": 380,
            "known_for_department": "Acting",
            "name": "Robert De Niro",
            "original_name": "Robert De Niro",
            "popularity": 91.34,
            "profile_path": "/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg",
            "cast_id": 16,
            "character": "Murray Franklin",
            "credit_id": "5b5242749251411f8600052d",
            "order": 1
        },
        {
            "adult": false,
            "gender": 1,
            "id": 1545693,
            "known_for_department": "Acting",
            "name": "Zazie Beetz",
            "original_name": "Zazie Beetz",
            "popularity": 28.76,
            "profile_path": "/ijrT4pvALvxU0gphea4YxDnDh6e.jpg",
            "cast_id": 15,
            "character": "Sophie Dumond",
            "credit_id": "5b5122a00e0a262596006a4c",
            "order": 2
        },
        {
            "adult": false,
            "gender": 1,
            "id": 4432,
            "known_for_department": "Acting",
            "name": "Frances Conroy",
            "original_name": "Frances Conroy",
            "popularity": 11.637,
            "profile_path": "/aJRQAkO24L6bH8qkkE5Iv1nA3gf.jpg",
            "cast_id": 17,
            "character": "Penny Fleck",
            "credit_id": "5b5636fcc3a3685c8e026bac",
            "order": 3
        },
        {
            "adult": false,
            "gender": 2,
            "id": 16841,
            "known_for_department": "Acting",
            "name": "Brett Cullen",
            "original_name": "Brett Cullen",
            "popularity": 9.033,
            "profile_path": "/4P6TsRcnr9MRbXlCdHitulGM5LT.jpg",
            "cast_id": 35,
            "character": "Thomas Wayne",
            "credit_id": "5b9fecf0c3a3680441002ee1",
            "order": 4
        },
        {
            "adult": false,
            "gender": 2,
            "id": 74242,
            "known_for_department": "Acting",
            "name": "Shea Whigham",
            "original_name": "Shea Whigham",
            "popularity": 12.243,
            "profile_path": "/d3caK3l4UfbnzOxv95wLoFLZzMO.jpg",
            "cast_id": 40,
            "character": "Detective Burke",
            "credit_id": "5ba0149092514177b20076a7",
            "order": 5
        },
        {
            "adult": false,
            "gender": 2,
            "id": 121718,
            "known_for_department": "Acting",
            "name": "Bill Camp",
            "original_name": "Bill Camp",
            "popularity": 9.08,
            "profile_path": "/yZFata0EVr7TbIAz8vZFyiDKDts.jpg",
            "cast_id": 37,
            "character": "Detective Garrity",
            "credit_id": "5ba0144fc3a3680441008c31",
            "order": 6
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1377670,
            "known_for_department": "Acting",
            "name": "Glenn Fleshler",
            "original_name": "Glenn Fleshler",
            "popularity": 8.101,
            "profile_path": "/x1Cef2yPZS7bJTwxI7DX3q0HNcv.jpg",
            "cast_id": 38,
            "character": "Randall",
            "credit_id": "5ba014700e0a2633c5008920",
            "order": 7
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1416396,
            "known_for_department": "Acting",
            "name": "Leigh Gill",
            "original_name": "Leigh Gill",
            "popularity": 3.901,
            "profile_path": "/bn9h4ovCuMj01OybjIoTrakOL2z.jpg",
            "cast_id": 64,
            "character": "Gary",
            "credit_id": "5ca5b79d9251415ebe6c3035",
            "order": 8
        },
        {
            "adult": false,
            "gender": 2,
            "id": 6181,
            "known_for_department": "Acting",
            "name": "Josh Pais",
            "original_name": "Josh Pais",
            "popularity": 9.306,
            "profile_path": "/uH90fGfLLzYCX02yOW3kH4LMO7n.jpg",
            "cast_id": 18,
            "character": "Hoyt Vaughn",
            "credit_id": "5b5d2363925141521a021d99",
            "order": 9
        },
        {
            "adult": false,
            "gender": 1,
            "id": 2504601,
            "known_for_department": "Acting",
            "name": "Rocco Luna",
            "original_name": "Rocco Luna",
            "popularity": 1.705,
            "profile_path": null,
            "cast_id": 286,
            "character": "GiGi Dumond",
            "credit_id": "5e168ee6cf4b8b0011806b59",
            "order": 10
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1231717,
            "known_for_department": "Acting",
            "name": "Marc Maron",
            "original_name": "Marc Maron",
            "popularity": 6.492,
            "profile_path": "/2ENNRs7lgbyLfrUN622zRqkYJWL.jpg",
            "cast_id": 19,
            "character": "Gene Ufland",
            "credit_id": "5b60965c0e0a267ee70001ea",
            "order": 11
        },
        {
            "adult": false,
            "gender": 1,
            "id": 171297,
            "known_for_department": "Acting",
            "name": "Sondra James",
            "original_name": "Sondra James",
            "popularity": 3.518,
            "profile_path": "/y0AuGOeO9qnVEu0oskPS2RrPNK1.jpg",
            "cast_id": 83,
            "character": "Dr. Sally",
            "credit_id": "5d9d0a8ea5046e003682bb15",
            "order": 12
        },
        {
            "adult": false,
            "gender": 2,
            "id": 155547,
            "known_for_department": "Acting",
            "name": "Murphy Guyer",
            "original_name": "Murphy Guyer",
            "popularity": 6.037,
            "profile_path": "/6axiNcYIZmaeRKyfCm3xBHC7KQL.jpg",
            "cast_id": 84,
            "character": "Barry O'Donnell",
            "credit_id": "5d9d0ab9a6e2d2001d4f274d",
            "order": 13
        },
        {
            "adult": false,
            "gender": 2,
            "id": 80149,
            "known_for_department": "Acting",
            "name": "Douglas Hodge",
            "original_name": "Douglas Hodge",
            "popularity": 6.07,
            "profile_path": "/ePGYx2w4cM9nSaBvfg9LdEieAtT.jpg",
            "cast_id": 39,
            "character": "Alfred Pennyworth",
            "credit_id": "5ba0147dc3a3680435008d5b",
            "order": 14
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1765331,
            "known_for_department": "Acting",
            "name": "Dante Pereira-Olson",
            "original_name": "Dante Pereira-Olson",
            "popularity": 2.314,
            "profile_path": "/zqo2pLRyjm1vIU1AVu2IWMDT8zN.jpg",
            "cast_id": 52,
            "character": "Bruce Wayne",
            "credit_id": "5c6dd9f30e0a262c99a1b8c0",
            "order": 15
        },
        {
            "adult": false,
            "gender": 1,
            "id": 2504604,
            "known_for_department": "Acting",
            "name": "Carrie Louise Putrello",
            "original_name": "Carrie Louise Putrello",
            "popularity": 1.25,
            "profile_path": "/jPsSCGPkgMAYh9NKcBJNUCW1FLv.jpg",
            "cast_id": 287,
            "character": "Martha Wayne",
            "credit_id": "5e168feecf4b8b0015805804",
            "order": 16
        },
        {
            "adult": false,
            "gender": 1,
            "id": 141748,
            "known_for_department": "Acting",
            "name": "Sharon Washington",
            "original_name": "Sharon Washington",
            "popularity": 5.453,
            "profile_path": "/zPQc0pv4aVbBE0w3cqMlRBZv1aS.jpg",
            "cast_id": 65,
            "character": "Social Worker",
            "credit_id": "5ca5b82dc3a36826c5af011e",
            "order": 17
        },
        {
            "adult": false,
            "gender": 1,
            "id": 1049916,
            "known_for_department": "Acting",
            "name": "Hannah Gross",
            "original_name": "Hannah Gross",
            "popularity": 14.064,
            "profile_path": "/2gsQ1btcduamJzvdmDE3XEdnhXl.jpg",
            "cast_id": 80,
            "character": "Young Penny",
            "credit_id": "5d985a8caaec71001a68174c",
            "order": 18
        },
        {
            "adult": false,
            "gender": 2,
            "id": 52021,
            "known_for_department": "Acting",
            "name": "Frank Wood",
            "original_name": "Frank Wood",
            "popularity": 4.484,
            "profile_path": "/er5hLYMwjAYb3saRQcNZED4rtgx.jpg",
            "cast_id": 288,
            "character": "Dr. Stoner",
            "credit_id": "5e1691081f748b0014852498",
            "order": 19
        },
        {
            "adult": false,
            "gender": 2,
            "id": 226366,
            "known_for_department": "Acting",
            "name": "Brian Tyree Henry",
            "original_name": "Brian Tyree Henry",
            "popularity": 11.593,
            "profile_path": "/2MsJh0bpyzwvOUnXOltHp3j85Pb.jpg",
            "cast_id": 61,
            "character": "Carl (Arkham Clerk)",
            "credit_id": "5ca47973c3a3685aad0c1d28",
            "order": 20
        },
        {
            "adult": false,
            "gender": 1,
            "id": 10691,
            "known_for_department": "Acting",
            "name": "April Grace",
            "original_name": "April Grace",
            "popularity": 10.406,
            "profile_path": "/nV8nnymN0ClT3xppwhlAtUnjSxa.jpg",
            "cast_id": 111,
            "character": "Arkham Psychiatrist",
            "credit_id": "5dc9d4177314a10018bc8c84",
            "order": 21
        },
        {
            "adult": false,
            "gender": 1,
            "id": 2504614,
            "known_for_department": "Acting",
            "name": "Mick Szal",
            "original_name": "Mick Szal",
            "popularity": 1.4,
            "profile_path": "/s3A3adaBlROorijl667bYm8FPN7.jpg",
            "cast_id": 289,
            "character": "Woman on Subway",
            "credit_id": "5e1692901f748b0016855ab9",
            "order": 22
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1546229,
            "known_for_department": "Acting",
            "name": "Carl Lundstedt",
            "original_name": "Carl Lundstedt",
            "popularity": 2.252,
            "profile_path": "/f2AGpZHxYoJthRIIahMx80NYcrc.jpg",
            "cast_id": 86,
            "character": "Wall Street Three",
            "credit_id": "5d9d0c4e4772150029028314",
            "order": 23
        },
        {
            "adult": false,
            "gender": 0,
            "id": 1556258,
            "known_for_department": "Acting",
            "name": "Michael Benz",
            "original_name": "Michael Benz",
            "popularity": 4.729,
            "profile_path": "/qb3oEBOpc11maO2CeM7SgbfWQEq.jpg",
            "cast_id": 87,
            "character": "Wall Street Three",
            "credit_id": "5d9d0c84f96a390040f6a4a0",
            "order": 24
        },
        {
            "adult": false,
            "gender": 0,
            "id": 2439980,
            "known_for_department": "Acting",
            "name": "Ben Warheit",
            "original_name": "Ben Warheit",
            "popularity": 0.98,
            "profile_path": "/nvyjIBONwEvLTL35rSEFMURo3y7.jpg",
            "cast_id": 290,
            "character": "Wall Street Three",
            "credit_id": "5e16952b0cb33500170430b7",
            "order": 25
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1123616,
            "known_for_department": "Acting",
            "name": "Gary Gulman",
            "original_name": "Gary Gulman",
            "popularity": 1.96,
            "profile_path": "/luX8IjBnUrfMAvpkkaGibX7feqG.jpg",
            "cast_id": 88,
            "character": "Comedian",
            "credit_id": "5d9d0cc6839018001e060740",
            "order": 26
        },
        {
            "adult": false,
            "gender": 2,
            "id": 2128773,
            "known_for_department": "Acting",
            "name": "Sam Morril",
            "original_name": "Sam Morril",
            "popularity": 1.026,
            "profile_path": "/aqYh6j4Wzv5PzEY7KEgmp6V3UW.jpg",
            "cast_id": 89,
            "character": "Open Mic Comic",
            "credit_id": "5d9d0ceea6e2d200414f2a0d",
            "order": 27
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1631358,
            "known_for_department": "Acting",
            "name": "Chris Redd",
            "original_name": "Chris Redd",
            "popularity": 2.289,
            "profile_path": "/nTisigWhjdQ10puFLTay9bqYl6s.jpg",
            "cast_id": 90,
            "character": "Comedy Club Emcee",
            "credit_id": "5d9d0d23a6e2d200414f2a59",
            "order": 28
        }
]

export default people;